name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.2
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test Network Monitor
      run: cd raspberry-network-monitor ; go test -v ./...

    - name: Build Network Monitor (Linux amd64)
      run: cd raspberry-network-monitor ; go build -v -o bin/network-monitor.linux.amd64 .
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Build Network Monitor (Raspbian - Raspberry Pi)
      run: cd raspberry-network-monitor ; go build -v -o bin/network-monitor.linux.arm .
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 5

    - name: Upload to Bintray Linux Arm
      run: curl -T bin/network-monitor.linux.arm -ueldius:${{secrets.BINTRAY_SECRET_KEY}} "https://api.bintray.com/content/eldius/network-manager-go/network-manager-go/0.0.1/network-monitor-go.linux.arm.$( git rev-parse --short HEAD )"

    - name: Upload to Bintray Linux amd64
      run: curl -T bin/network-monitor.linux.amd64 -ueldius:${{secrets.BINTRAY_SECRET_KEY}} "https://api.bintray.com/content/eldius/network-manager-go/network-manager-go/0.0.1/network-monitor-go.linux.amd64.$( git rev-parse --short HEAD )"
