name: raspberry-simplemqtt-listener-go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.2
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test Network Monitor
      run: cd raspberry-simplemqtt-listener ; go test -v ./...

    - name: Build Network Monitor (Linux amd64)
      run: |
        cd raspberry-simplemqtt-listener ; \
        go build -v \
          -ldflags \
          "-X 'github.com/Eldius/raspberry-monitor-projects/raspberry-network-monitor/cmd.buildDate=$(date +"%Y-%m-%dT%H:%M:%S%:z")' -X 'github.com/Eldius/raspberry-monitor-projects/raspberry-network-monitor/cmd.gitCommit=$(git log -n 1 --format=%h)'" \
          -o bin/simplemqtt-listener.linux.amd64 .
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Build Network Monitor (Raspbian - Raspberry Pi)
      run: |
        cd raspberry-simplemqtt-listener ; \
        go build -v \
          -ldflags \
          "-X 'github.com/Eldius/raspberry-monitor-projects/raspberry-network-monitor/cmd.buildDate=$(date +"%Y-%m-%dT%H:%M:%S%:z")' -X 'github.com/Eldius/raspberry-monitor-projects/raspberry-network-monitor/cmd.gitCommit=$(git log -n 1 --format=%h)'" \
          -o bin/simplemqtt-listener.linux.arm .
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 7

    - name: Create Bintray Package
      run: |
        curl -i -X POST 'https://api.bintray.com/packages/eldius/raspberry-tools' \
          -ueldius:${{secrets.BINTRAY_SECRET_KEY}} \
          -H 'Content-Type: application/json' \
          -d '{
              "name": "simplemqtt-listener",
              "desc": "simplemqtt-listener",
              "labels": ["http", "test", "app"],
              "licenses": ["GPL-3.0"],
              "vcs_url": "https://github.com/Eldius/raspberry-tools.git",
              "website_url": "https://github.com/Eldius/raspberry-tools",
              "public_download_numbers": true,
              "public_stats": true
          }'

    - name: Create Bintray Version
      run: |
        curl -i -X POST 'https://api.bintray.com/packages/eldius/raspberry-tools/simplemqtt-listener/versions' \
          -ueldius:${{secrets.BINTRAY_SECRET_KEY}} \
          -H 'Content-Type: application/json' \
          -d '{
            "name": "develop"
          }'

    - name: Upload to Bintray Linux Arm
      run: |
        curl -i \
          -H "X-GPG-PASSPHRASE: ${{secrets.BINTRAY_SIGNIN_KEY}}" \
          -X PUT \
          -T raspberry-simplemqtt-listener/bin/simplemqtt-listener.linux.arm \
          -ueldius:${{secrets.BINTRAY_SECRET_KEY}} \
          "https://api.bintray.com/content/eldius/raspberry-tools/simplemqtt-listener/development/simplemqtt-listener.linux.arm.$( git rev-parse --short HEAD );publish=1;override=1"

    - name: Upload to Bintray Linux amd64
      run: |
        curl -i \
          -H "X-GPG-PASSPHRASE: ${{secrets.BINTRAY_SIGNIN_KEY}}" \
          -X PUT \
          -T raspberry-simplemqtt-listener/bin/simplemqtt-listener.linux.amd64 \
          -ueldius:${{secrets.BINTRAY_SECRET_KEY}} \
          "https://api.bintray.com/content/eldius/raspberry-tools/simplemqtt-listener/development/simplemqtt-listener.linux.amd64.$( git rev-parse --short HEAD );publish=1;override=1"
